language: python
python: 3.8

services:
  - docker

install:
  - pip install codecov

script:
  - cp .env.example .env
  - docker-compose up -d
  - docker-compose exec web pytest -v
  - docker-compose exec coverage run app/test_main.py

after_success:
  - codecov