language: python
python: 3.8

services:
  - mongodb

before_install:
  - pip install requirements.txt

install:
  - pip install codecov

env:
  - MONGO_INITDB_ROOT_USERNAME=SomeUsername MONGO_INITDB_ROOT_PASSWORD=SomePassword MONGO_HOST=db MONGO_PORT=27017

script:
  - pytest

after_success:
  - codecov