language: python
python: 3.8

services:
  - docker

install:
  - pip install codecov

env:
  - MONGO_INITDB_ROOT_USERNAME=SomeUsername MONGO_INITDB_ROOT_PASSWORD=SomePassword MONGO_HOST=db MONGO_PORT=27017

script:
  - cp .env.example .env
  - docker-compose up -d
  - docker-compose exec web pytest -v

after_success:
  - codecov