language: python
python: 3.8

services:
  - docker

before_install:
  - pip install docker-compose

install:
  - pip install codecov

script:
  - docker-compose run app sh -c "pytest"

after_success:
  - codecov