language: python
python: 3.8

services:
  - docker
  - mongodb

before_install:
  - pip install docker-compose

install:
  - pip install codecov

env:
  - MONGO_INITDB_ROOT_USERNAME=SomeUsername MONGO_INITDB_ROOT_PASSWORD=SomePassword MONGO_HOST=db MONGO_PORT=27017

script:
  - docker-compose --env-file ./.env.example run app sh -c "pytest"

after_success:
  - codecov